import { describe, expect, it } from "vitest";
import { labelGeometry, trianglePath, axisLabelPlacement, type LabelAesthetics, type LabelState } from "../src/rendering/index";

const aesthetics: LabelAesthetics = {
  label_position: "top", label_y_offset: 20, label_line_offset: 5, label_angle_offset: 0,
  label_font: "Arial", label_size: 10, label_colour: "#000000", label_line_max_length: 1000,
  label_marker_show: true, label_marker_offset: 5, label_marker_size: 3,
  label_marker_colour: "#000000", label_marker_outline_colour: "#000000"
};

function label(overrides: Partial<LabelAesthetics>, angle?: number, distance?: number): LabelState {
  return { text_value: "A", aesthetics: { ...aesthetics, ...overrides }, angle, distance };
}

function must<T>(value: T | undefined): T {
  if (value === undefined) throw new Error("Expected geometry");
  return value;
}

describe("label geometry", () => {
  it("places a top label straight up, limited by the top offset", () => {
    const g = must(labelGeometry(label({}), 100, 150, 400, 30));
    expect(g.theta).toBe(-90);
    expect(g.x).toBeCloseTo(100, 10);
    expect(g.y).toBeCloseTo(20, 10);
    expect(g.line_offset).toBe(5);
    expect(g.marker_offset).toBe(-10);
  });

  it("places a bottom label straight down, limited by the axis offset", () => {
    const g = must(labelGeometry(label({ label_position: "bottom" }), 100, 150, 400, 30));
    expect(g.theta).toBe(90);
    expect(g.x).toBeCloseTo(100, 10);
    expect(g.y).toBeCloseTo(350, 10);
    expect(g.line_offset).toBe(-10);
    expect(g.marker_offset).toBe(10);
  });

  it("caps the connector at the maximum line length and applies the angle offset", () => {
    const g = must(labelGeometry(label({ label_line_max_length: 50, label_angle_offset: 30 }), 100, 150, 400, 30));
    expect(g.theta).toBe(-60);
    expect(g.x).toBeCloseTo(100 + 50 * Math.cos(-Math.PI / 3), 10);
    expect(g.y).toBeCloseTo(150 + 50 * Math.sin(-Math.PI / 3), 10);
  });

  it("uses a dragged angle and distance over the computed placement", () => {
    const g = must(labelGeometry(label({}, 0, 7), 100, 150, 400, 30));
    expect(g.theta).toBe(0);
    expect(g.x).toBeCloseTo(107, 10);
    expect(g.y).toBeCloseTo(150, 10);
  });

  // Finding 30: only non-finite positions are missing; the origin is an ordinary position
  it("returns no geometry for a non-finite position and keeps the origin", () => {
    expect(labelGeometry(label({}, NaN, 7), 100, 150, 400, 30)).toBeUndefined();
    expect(labelGeometry(label({}, 0, Infinity), 100, 150, 400, 30)).toBeUndefined();
    const origin = must(labelGeometry(label({}, 0, 0), 0, 0, 400, 30));
    expect(origin.x).toBe(0);
    expect(origin.y).toBe(0);
  });
});

describe("triangle marker path", () => {
  // Reference strings generated by d3-shape 3.2.0 symbol().type(symbolTriangle).size(s)()
  it.each([
    [0, "M0,0L0,0L0,0Z"],
    [1, "M0,-0.877L0.76,0.439L-0.76,0.439Z"],
    [4, "M0,-1.755L1.52,0.877L-1.52,0.877Z"],
    [9, "M0,-2.632L2.28,1.316L-2.28,1.316Z"],
    [10, "M0,-2.775L2.403,1.387L-2.403,1.387Z"],
    [12.25, "M0,-3.071L2.659,1.535L-2.659,1.535Z"],
    [100, "M0,-8.774L7.598,4.387L-7.598,4.387Z"]
  ])("matches d3 for size %s", (size, expected) => {
    expect(trianglePath(size)).toBe(expected);
  });
});

describe("axis label placement", () => {
  it("anchors left and bottom at the start, right and top at the end", () => {
    expect(axisLabelPlacement("left", 60, 480)).toEqual({ position: 60, anchor: "start" });
    expect(axisLabelPlacement("right", 60, 480)).toEqual({ position: 480, anchor: "end" });
    // Centred on the plot area, not the canvas, so uneven padding does not skew it
    expect(axisLabelPlacement("center", 60, 480)).toEqual({ position: 270, anchor: "middle" });
    // The rotated y label runs upward, so its start is the bottom of the plot
    expect(axisLabelPlacement("bottom", 490, 10)).toEqual({ position: 490, anchor: "start" });
    expect(axisLabelPlacement("top", 490, 10)).toEqual({ position: 10, anchor: "end" });
  });
});
